'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const assets=require('../../data/v2/formal-battle-assets.js'),characters=require('../../data/v2/characters.js').characters,skills=require('../../data/v2/skills.js'),ui=require('../../js/v2/formal-battle-ui.js');let passed=0;
function test(n,f){try{f();passed++;process.stdout.write('ok - '+n+'\n');}catch(e){process.stderr.write('not ok - '+n+'\n'+e.stack+'\n');process.exitCode=1;}}
const source=n=>fs.readFileSync(path.join(__dirname,'../../',n),'utf8');
test('asset approval metadata is explicit',()=>{assert.equal(assets.resolve('portrait.sora').approval,'candidate');assert.equal(assets.resolve('enemy.legacyDailyCore').approval,'legacyPlaceholder');});
test('repository paths are local',()=>Object.values(assets.ASSETS).forEach(a=>assert.equal(/^(?:https?:|\/\/|data:)/.test(a.path),false)));
test('field and HUD keys are separate',()=>['sora','aria','ceres','linnet'].forEach(id=>{assert.equal(characters[id].fieldAssetKey,null);assert.ok(characters[id].hudPortraitAssetKey.startsWith('portrait.'));}));
test('candidate HUD is preview-only',()=>{class N{constructor(){this.children=[];this.style={};this.attributes={};this.className='';this.parentNode=null;}appendChild(n){n.parentNode=this;this.children.push(n);return n;}removeChild(n){this.children.splice(this.children.indexOf(n),1);n.parentNode=null;}get firstChild(){return this.children[0]||null;}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(){}}const doc={createElement:()=>new N()},snap={partySlots:{protagonist:{characterId:'sora'},supporter:{characterId:'aria'},defender:{characterId:'ceres'},attacker:{characterId:'linnet'}},charactersById:{sora:{},aria:{},ceres:{},linnet:{}},enemyOrder:[],enemiesById:{}};const count=(n,c)=>[n,...n.children.flatMap(x=>[x,...x.children])].filter(x=>x.className===c).length;const render=p=>{const x=ui.create({document:doc,host:new N(),definitions:{characters,skills},allowNonFormalPreviewAssets:p});x.render(snap,{locked:false});return x;};assert.equal(count(render(false).registry['hud-protagonist'],'bn2-portrait-art'),0);assert.equal(count(render(false).registry['hud-protagonist'],'bn2-portrait-placeholder'),1);assert.equal(count(render(true).registry['hud-protagonist'],'bn2-portrait-art'),1);assert.equal(assets.resolve('portrait.sora').approval,'candidate');});
test('missing field falls back safely',()=>assert.ok(source('js/v2/formal-battle-ui.js').includes("definition.fieldAssetKey || 'missing'")));
test('legacy and candidate are not formal',()=>Object.values(assets.ASSETS).forEach(a=>assert.notEqual(a.approval,'formal')));
test('metadata has no battle values',()=>Object.values(assets.ASSETS).forEach(a=>assert.equal(Object.hasOwn(a,'damage'),false)));
test('FX adapter stays separate',()=>assert.equal(/formalBattleAssets|images\//.test(source('js/v2/battle-fx-adapter.js')),false));
test('no external URL or unsafe HTML',()=>{const s=['data/v2/formal-battle-assets.js','js/v2/formal-battle-ui.js','css/formal-battle-ui-v2.css'].map(source).join('\n');[/https?:\/\//,/innerHTML/,/eval\s*\(/,/new\s+Function/,/\bfetch\s*\(/].forEach(p=>assert.equal(p.test(s),false));});
test('viewport loads registry first',()=>{const s=source('tests/v2/formal-battle-viewport.html');assert.ok(s.indexOf('formal-battle-assets.js')<s.indexOf('formal-battle-ui.js'));});
process.on('exit',()=>{if(!process.exitCode)process.stdout.write('# '+passed+' Phase F tests passed\n');});
