'use strict';
require('./phase-a.test.js');
require('./phase-b.test.js');
require('./phase-c.test.js');
require('./phase-d.test.js');
require('./phase-e.test.js');
require('./phase-f.test.js');
require('./phase-g.test.js');
require('./production-verification-entry.test.js');
require('./stage1-rule-alignment.test.js');
require('./stage2-daily-attack-gate.test.js');
require('./stage3-mission-lifecycle.test.js');
require('./stage3-calendar-lifecycle.test.js');
require('./stage3-enemy-lifecycle.test.js');
require('./stage3-lifecycle-integration.test.js');
