'use strict';
const {assert,code,clone,initialized,memory}=require('./stage3-mission-lifecycle.test.js');
const {descriptor,definitions,provider}=require('./stage3-enemy-lifecycle.test.js');
const schema=require('../../js/v2/schema.js'),week=require('../../js/v2/week-lifecycle.js'),coordinator=require('../../js/v2/lifecycle-coordinator.js'),repo=require('../../js/v2/save-repository.js');
const equal=(a,b)=>assert.deepEqual(a===undefined?a:clone(a),b===undefined?b:clone(b));
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3B Week: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3B Week: '+name+'\n'+e.stack);}}
function context(s,index=1,date=s.calendar.localDate,weekKey=s.calendar.weekKey){return {date,weekKey,areaId:s.profile.currentAreaId,areaWeekIndex:index,weekRole:index===4?'areaBoss':'weekly'};}
function state(index=1){const s=initialized().state;s.calendar.weekContext={...context(s,index),degradedWeeklySourceEncounterDescriptorId:index===4?'source-week3':null};delete s.calendar.weekContext.date;return s;}
function character(s,id,resources={},flags={}){const d=definitions.characters.characters[id];s.charactersById[id]={characterId:id,hp:d.maxHp===null?null:0,sp:d.maxSp===null?null:2,barrier:null,statusIds:[],resources,flags,weekly:{},battle:null};return s.charactersById[id];}
function boss(c){const d=descriptor(c.startDate,'boss-'+c.weekKey,'boss-desc-'+c.weekKey),kind=c.state.calendar.weekContext.weekRole;d.kind=d.enemy.kind=kind;d.definitionId=d.enemy.definitionId=kind==='areaBoss'?'area_boss_base':'weekly_base';delete d.encounterRole;delete d.enemy.flags.encounterRole;return d;}
function setup(s=state(),target='2026-09-28',boundary){const f=initialized(),storage=memory(),repository=repo.create(storage);repository.saveInitialState(s);const options={repository,operationRepository:{load:()=>null},clock:()=>target+'T12:00:00+09:00',assignmentRefPolicy:f.policy,definitions,dailyEncounterProvider:provider,weeklyEncounterProvider:{forWeek:boss},boundaryProvider:{forDate:boundary||((c)=>context(s,c.date===s.calendar.localDate?s.calendar.weekContext.areaWeekIndex:s.calendar.weekContext.areaWeekIndex+1,c.date,c.date===s.calendar.localDate?s.calendar.weekKey:'trusted-next'))}};return {storage,repository,options,api:()=>coordinator.create(options)};}
function stop(x,error){const bytes=[...x.storage.map],w=x.storage.writes;code(()=>x.api().advanceCalendar(),error);assert.equal(x.storage.writes,w);equal([...x.storage.map],bytes);}
for(const value of [undefined,null])test('legacy weekContext '+String(value)+' valid schemaVersion2',()=>{const s=state();if(value===undefined)delete s.calendar.weekContext;else s.calendar.weekContext=value;assert.equal(schema.validateState(s).ok,true);assert.equal(s.schemaVersion,2);});
for(let index=1;index<=4;index++)test('exact persistent context index '+index,()=>assert.equal(schema.validateState(state(index)).ok,true));
for(const [name,mutate] of [['extra',c=>c.extra=true],['missing',c=>delete c.areaId],['week mismatch',c=>c.weekKey='other'],['area mismatch',c=>c.areaId='other'],['zero index',c=>c.areaWeekIndex=0],['invalid role',c=>c.weekRole='areaBoss'],['unexpected source',c=>c.degradedWeeklySourceEncounterDescriptorId='source']])test('schema rejects '+name,()=>{const s=state();mutate(s.calendar.weekContext);assert.equal(schema.validateState(s).ok,false);});
test('week4 source required and weekly role forbidden',()=>{for(const change of [c=>c.degradedWeeklySourceEncounterDescriptorId=null,c=>c.weekRole='weekly']){const s=state(4);change(s.calendar.weekContext);assert.equal(schema.validateState(s).ok,false);}});
test('same-day initial binding one CAS; retry and reload zero write',()=>{const s=state();delete s.calendar.weekContext;const x=setup(s,s.calendar.localDate,c=>context(s,1,c.date)),w=x.storage.writes;const result=x.api().advanceCalendar();assert.equal(x.storage.writes-w,2);assert.equal(Object.keys(result.calendar.weekContext).length,5);x.api().advanceCalendar();assert.equal(x.storage.writes-w,2);equal(x.repository.loadState().state.calendar.weekContext,result.calendar.weekContext);});
test('first binding week mismatch never corrects stored week',()=>{const s=state();delete s.calendar.weekContext;stop(setup(s,s.calendar.localDate,c=>context(s,1,c.date,'different')),'WEEK_CONTEXT_CONFLICT');});
test('old week4 binding has no inferred source',()=>{const s=state();delete s.calendar.weekContext;stop(setup(s,s.calendar.localDate,c=>context(s,4,c.date)),'DEGRADED_WEEKLY_SOURCE_UNRESOLVED');});
for(const [name,change] of [['area',c=>c.areaId='other'],['index',c=>c.areaWeekIndex=2],['role',c=>{c.areaWeekIndex=4;c.weekRole='areaBoss';}]])test('same-week '+name+' drift write0',()=>{const s=state();stop(setup(s,s.calendar.localDate,c=>{const v=context(s,1,c.date);change(v);return v;}),'WEEK_CONTEXT_CONFLICT');});
for(const index of [1,2,3])test('adjacent '+index+' -> '+(index+1)+' with trusted boss and Daily',()=>{const s=state(index);if(index===3){const b=boss({startDate:s.calendar.localDate,weekKey:s.calendar.weekKey,state:s});s.enemiesById={[b.instanceId]:b.enemy};s.enemyOrder=[b.instanceId];}const x=setup(s);if(index===3)x.options.dailyEncounterProvider={forDate:c=>{const d=descriptor(c.date);d.encounterRole='degradedWeeklyClone';delete d.enemy.flags.encounterRole;d.sourceEncounterDescriptorId=c.state.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId;return d;}};const before=clone(s),next=x.api().advanceCalendar();assert.equal(next.calendar.weekContext.areaWeekIndex,index+1);assert.equal(next.enemyOrder.length,2);assert.equal(next.enemiesById[next.enemyOrder[0]].kind,index===3?'areaBoss':'weekly');equal(next.profile,before.profile);equal(next.partySlots,before.partySlots);equal(next.leaderCarry,before.leaderCarry);equal(next.missions.special,before.missions.special);assert.equal(next.missions.weekly.clearCount,0);equal(next.missions.weekly.completedIds,[]);assert.equal(next.missions.weekly.weekKey,'trusted-next');equal(next.missions.weekly.slots,before.missions.weekly.slots);if(index===3)assert.equal(next.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId,'boss-desc-'+s.calendar.weekKey);});
for(const [from,to] of [[1,3],[3,2],[4,1]])test('nonadjacent '+from+' -> '+to+' STOP',()=>{const s=state(from);stop(setup(s,'2026-09-28',c=>context(s,c.date===s.calendar.localDate?from:to,c.date,c.date===s.calendar.localDate?s.calendar.weekKey:'new')),'WEEK_CONTEXT_CONFLICT');});
test('Area transition HOLD storage0',()=>{const s=state(4);stop(setup(s,'2026-09-28',c=>({...context(s,4,c.date,c.date===s.calendar.localDate?s.calendar.weekKey:'other'),areaId:c.date===s.calendar.localDate?s.profile.currentAreaId:'new-area'})),'AREA_TRANSITION_STAGE3B_HOLD');});
for(const problem of ['none','multiple','missing','invalid'])test('3 -> 4 source '+problem+' STOP before reset',()=>{const s=state(3);s.enemiesById={};s.enemyOrder=[];if(problem!=='none'){const b=boss({startDate:s.calendar.localDate,weekKey:s.calendar.weekKey,state:s});if(problem==='missing')delete b.enemy.flags.encounterDescriptorId;if(problem==='invalid')b.enemy.flags.encounterDescriptorId='';s.enemiesById[b.instanceId]=b.enemy;s.enemyOrder=[b.instanceId];if(problem==='multiple'){const e=clone(b.enemy);e.instanceId='second';e.hp=0;e.defeated=true;s.enemiesById.second=e;s.enemyOrder.push('second');}}stop(setup(s),'DEGRADED_WEEKLY_SOURCE_UNRESOLVED');});
test('defeated week3 record is source before old-enemy reset',()=>{const s=state(3),b=boss({startDate:s.calendar.localDate,weekKey:s.calendar.weekKey,state:s});b.enemy.defeated=true;b.enemy.hp=0;s.enemiesById={[b.instanceId]:b.enemy};s.enemyOrder=[b.instanceId];const w=week.create({assignmentRefPolicy:initialized().policy,definitions,weeklyEncounterProvider:{forWeek:boss}});const n=w.transition(s,context(s,4,'2026-09-28','new'));assert.equal(n.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId,b.encounterDescriptorId);assert.equal(n.enemiesById[b.instanceId],undefined);});
for(const [name,provider,error] of [['none',null,'WEEKLY_ENCOUNTER_UNCONFIGURED'],['empty',{forWeek:()=>null},'WEEKLY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED'],['wrong definition',{forWeek:c=>{const d=boss(c);d.definitionId=d.enemy.definitionId='daily_base';return d;}},'WEEKLY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED'],['missing HP',{forWeek:c=>{const d=boss(c);delete d.enemy.hp;return d;}},'WEEKLY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED']])test('Weekly provider '+name+' no fallback write0',()=>{const x=setup();x.options.weeklyEncounterProvider=provider;stop(x,error);});
test('offline days and week transition pure preview then one CAS; failure storage0',()=>{const s=state(),x=setup(s,'2026-09-30',c=>context(s,c.date<'2026-09-29'?1:2,c.date,c.date<'2026-09-29'?s.calendar.weekKey:'new')),before=[...x.storage.map],w=x.storage.writes;const preview=x.api().simulateCalendar(s);equal([...x.storage.map],before);assert.equal(preview.calendar.localDate,'2026-09-30');equal(x.api().advanceCalendar(),preview);assert.equal(x.storage.writes-w,2);const y=setup(s,'2026-09-30',x.options.boundaryProvider.forDate);y.options.dailyEncounterProvider={forDate:c=>c.date==='2026-09-30'?null:descriptor(c.date)};stop(y,'DAILY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED');});
test('offline two trusted adjacent week transitions remain one CAS',()=>{const s=state(),x=setup(s,'2026-09-29',c=>context(s,c.date===s.calendar.localDate?1:c.date==='2026-09-28'?2:3,c.date,c.date===s.calendar.localDate?s.calendar.weekKey:'week-'+c.date)),w=x.storage.writes;const n=x.api().advanceCalendar();assert.equal(n.calendar.weekContext.areaWeekIndex,3);assert.equal(x.storage.writes-w,2);});
test('stale CAS rejects without field merge',()=>{const x=setup(),before=x.repository.loadState().state,n=x.api().simulateCalendar(before),changed=clone(before);changed.profile.points++;x.storage.map.set(repo.KEYS.state,JSON.stringify(changed));const w=x.storage.writes;code(()=>x.repository.commitStateTransition(before,n,()=>true),'STATE_CONFLICT');assert.equal(x.storage.writes,w);});
test('reserved and pending STOP with no provider calls',()=>{const x=setup();let calls=0;x.options.boundaryProvider={forDate:()=>{calls++;throw Error('forbidden');}};x.options.operationRepository={load:()=>({dailyAttack:{status:'reserved'}})};stop(x,'ATTACK_RESERVATION_UNRESOLVED');assert.equal(calls,0);x.options.operationRepository={load:()=>null};x.options.repository={loadPending:()=>({pending:true})};stop(x,'NON_BATTLE_PENDING');assert.equal(calls,0);});
test('trusted weekly configuration replaces only on period boundary; mutable STOP',()=>{const x=setup(),slots=clone(x.repository.loadState().state.missions.weekly.slots);slots[0].assignmentRef='new-weekly-revision';slots[0].pointValue=9;x.options.assignmentRefPolicy.records.set(slots[0].assignmentRef,{immutable:true,pointValue:9,content:{label:'new'}});x.options.missionConfigurationProvider={forPeriod:c=>c.kind==='weekly'?{slots}:null};assert.equal(x.api().advanceCalendar().missions.weekly.slots[0].pointValue,9);const y=setup();y.options.missionConfigurationProvider={forPeriod:c=>c.kind==='weekly'?{slots}:null};stop(y,'MISSION_ASSIGNMENT_REF_NOT_IMMUTABLE');});
test('canonical HP/status/Aria/Irina/Ceres/Myart reset; keep resources',()=>{const s=state();for(const id of Object.keys(definitions.characters.characters))character(s,id);s.charactersById.aria.resources={debtBySourceId:{'daily-source':{damage:99,mainActionMarks:7}}};s.charactersById.irina.resources={reinforcementUsageByCharacterId:{aria:true}};s.charactersById.ceres.resources={reserveHp:50,weeklyBarrierLoss:20};s.charactersById.ceres.flags={recoveryLocked:true};s.charactersById.myart.resources={researchKits:3,weaknessMaterials:{x:2},otherMaterials:4,reserveSp:null};s.charactersById.myart.flags={weaknessProtocolDeveloped:true};s.charactersById.linnet.resources={tameRoster:{fixture:true}};s.battleProgress.suPoints=4;s.battleProgress.dailySuUsedOn=s.calendar.localDate;s.battleProgress.pendingElliottHits={amount:3,expiresOn:'2026-09-28'};for(const statusId of ['poison','burn','freeze','bind','gravity','finalHour'])s.statusInstances[statusId]={statusId,clearsAtWeekStart:false};s.charactersById.aria.statusIds=['poison','finalHour'];const old=clone(s),n=week.resetCharacters(s,definitions);for(const [id,c] of Object.entries(n.charactersById)){assert.equal(c.hp,definitions.characters.characters[id].maxHp);assert.equal(c.sp,old.charactersById[id].sp);assert.equal(c.barrier,null);equal(c.statusIds,[]);}equal(n.statusInstances,{});equal(n.charactersById.aria.resources.debtBySourceId,{});equal(n.charactersById.irina.resources.reinforcementUsageByCharacterId,{});equal(n.charactersById.ceres.resources,{reserveHp:0,weeklyBarrierLoss:0});assert.equal(n.charactersById.ceres.flags.recoveryLocked,false);assert.equal(n.charactersById.myart.flags.weaknessProtocolDeveloped,false);equal(n.charactersById.myart.resources,old.charactersById.myart.resources);equal(n.charactersById.linnet.resources,old.charactersById.linnet.resources);equal(n.battleProgress,old.battleProgress);equal(s,old);});
for(const statusId of ['poison','burn','freeze','bind','gravity','finalHour'])test('formal status '+statusId+' metadata true and persisted false cleared',()=>{assert.equal(definitions.statusEffects.effects[statusId].clearsAtWeekStart,true);const s=state();s.statusInstances.x={statusId,clearsAtWeekStart:false};s.charactersById.aria.statusIds=['x'];const n=week.resetCharacters(s,definitions);equal(n.statusInstances,{});equal(n.charactersById.aria.statusIds,[]);});
for(const jackpot of [false,true])test('Sierra jackpot '+jackpot+' canonical exception',()=>{const s=state();character(s,'sierra',{faceCoins:27,jackpot,coinTossAudit:{}});const n=week.resetCharacters(s,definitions);assert.equal(n.charactersById.sierra.resources.faceCoins,jackpot?10:27);assert.equal(n.charactersById.sierra.sp,jackpot?5:2);assert.equal(n.charactersById.sierra.resources.jackpot,false);});
for(const v of [null,{}])test('inactive Sierra coinTossAudit '+JSON.stringify(v)+' preserved',()=>{const s=state();character(s,'sierra',{coinTossAudit:v});equal(week.resetCharacters(s,definitions).charactersById.sierra.resources.coinTossAudit,v);});
for(const [id,resource,value,error] of [['aria','debtBySourceId',[],'WEEK_BOUNDARY_RESOURCE_INVALID'],['irina','reinforcementUsageByCharacterId',{aria:false},'WEEK_BOUNDARY_RESOURCE_INVALID'],['ceres','reserveHp',1.5,'WEEK_BOUNDARY_RESOURCE_INVALID'],['ceres','weeklyBarrierLoss',-1,'WEEK_BOUNDARY_RESOURCE_INVALID'],['sierra','coinTossAudit',{coin:1},'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['rg','reversalRune',{},'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['rg','reversalRune',false,'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['rg','reversalRune',{active:true},'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['rg','runesByStatusId',{poison:{}},'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['myart','reserveSp',1,'DAY_BOUNDARY_EFFECT_UNRESOLVED'],['elliott','pendingAttackerHits',null,'WEEK_BOUNDARY_EFFECT_UNRESOLVED'],['noel','mealTicks',2,'WEEK_BOUNDARY_EFFECT_UNRESOLVED']])test(id+' '+resource+' '+JSON.stringify(value)+' fail-closed',()=>{const s=state();character(s,id,{[resource]:value});const bytes=JSON.stringify(s);code(()=>week.resetCharacters(s,definitions),error);assert.equal(JSON.stringify(s),bytes);});
test('RG reversalRune missing/null allowed, no invented shape',()=>{for(const r of [{},{reversalRune:null}]){const s=state();character(s,'rg',r);equal(week.resetCharacters(s,definitions).charactersById.rg.resources,r);}});
for(const mutate of [s=>character(s,'sierra',{faceCoins:'bad',jackpot:true}),s=>{character(s,'sierra',{faceCoins:3,jackpot:true}).sp=null;},s=>{character(s,'ceres',{}, {recoveryLocked:1});}])test('invalid resource canonical shape rejected',()=>{const s=state();mutate(s);code(()=>week.resetCharacters(s,definitions),'WEEK_BOUNDARY_RESOURCE_INVALID');});
for(const mutate of [s=>s.charactersById.aria.weekly={used:true},s=>s.charactersById.aria.resources.unknown={active:true},s=>s.charactersById.aria.flags.unknown=true])test('unknown active weekly/resource/flag STOP',()=>{const s=state();mutate(s);code(()=>week.resetCharacters(s,definitions),'WEEK_BOUNDARY_EFFECT_UNRESOLVED');});
test('unknown character and invalid definition maxHP stop without hardcoded repair',()=>{const s=state();s.charactersById.unknown=clone(s.charactersById.aria);code(()=>week.resetCharacters(s,definitions),'WEEK_CHARACTER_DEFINITION_UNRESOLVED');const defs=clone(definitions);defs.characters.characters.aria.maxHp=0;code(()=>week.resetCharacters(state(),defs),'WEEK_CHARACTER_DEFINITION_UNRESOLVED');});
test('KEEP validator rejects Party/Leader/points/carry/resource tampering',()=>{const s=state(),n=week.resetCharacters(s,definitions);n.calendar.weekKey='new';for(const change of [a=>a.profile.points++,a=>a.profile.selectedLeaderCharacterId='aria',a=>a.partySlots=['aria'],a=>a.leaderCarry.extra=true,a=>a.charactersById.aria.sp=4]){const bad=clone(n);change(bad);code(()=>week.validateTransition(s,bad,definitions),'INVALID_STATE_TRANSITION');}});
console.log(`# ${passed}/${total} Stage 3B Week tests passed`);
module.exports={state,context,character,boss,setup,stop};
