'use strict';
const {assert,code,clone,initialized,minimal,configuration,policy,memory,events}=require('./stage3-mission-lifecycle.test.js');
const {descriptor,definitions,provider}=require('./stage3-enemy-lifecycle.test.js');
const repoApi=require('../../js/v2/save-repository.js'),controllerApi=require('../../js/v2/battle-controller.js'),calculator=require('../../js/v2/battle-calculator.js'),coordinatorApi=require('../../js/v2/lifecycle-coordinator.js'),schema=require('../../js/v2/schema.js');
function setup(state){const fixture=initialized(),storage=memory(),repository=repoApi.create(storage);repository.saveInitialState(state||fixture.state);let operation=null;const options={repository,operationRepository:{load:()=>clone(operation)},clock:()=> '2026-09-27T12:00:00+09:00',assignmentRefPolicy:fixture.policy,boundaryProvider:{forDate:c=>({date:c.date,weekKey:c.weekKey})},dailyEncounterProvider:provider,definitions};return {storage,repository,options,coordinator:coordinatorApi.create(options),setOperation:v=>{operation=v;}};}
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3 Integration: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3 Integration: '+name+'\n'+e.stack);}}
const op=status=>({version:1,timezone:'Asia/Tokyo',dailyAttack:{dayKey:'2026-09-27',status,reservationId:'r',battleId:'b',dailyResult:1}});
function bytes(x){return [...x.storage.map];}
test('nonBattle CAS writes backup then next and verifies both reads',()=>{const x=setup(),expected=x.repository.loadState().state,next=clone(expected);next.profile.points++;const trace=[],get=x.storage.getItem,set=x.storage.setItem;x.storage.getItem=k=>{trace.push('read '+k);return get(k);};x.storage.setItem=(k,v)=>{trace.push('write '+k);set(k,v);};const result=x.repository.commitStateTransition(expected,next,()=>{trace.push('domain');return true;});assert.equal(result.profile.points,next.profile.points);assert.deepEqual(trace.slice(-4),['write '+repoApi.KEYS.backup,'read '+repoApi.KEYS.backup,'write '+repoApi.KEYS.state,'read '+repoApi.KEYS.state]);assert.equal(x.storage.getItem(repoApi.KEYS.backup),JSON.stringify(expected));assert.equal(result.revision,expected.revision);assert.equal(result.writtenAt,expected.writtenAt);});
test('CAS rejects stale expected without merge or storage writes',()=>{const x=setup(),expected=x.repository.loadState().state,next=clone(expected);expected.profile.points++;next.profile.points+=2;const before=bytes(x),writes=x.storage.writes;code(()=>x.repository.commitStateTransition(expected,next,()=>true),'STATE_CONFLICT');assert.equal(x.storage.writes,writes);assert.deepEqual(bytes(x),before);});
test('CAS requires domain invariant before schema/write',()=>{const x=setup(),s=x.repository.loadState().state,next=clone(s);next.profile.points++;const before=bytes(x);code(()=>x.repository.commitStateTransition(s,next),'TRANSITION_POLICY_REQUIRED');code(()=>x.repository.commitStateTransition(s,next,()=>false),'INVALID_STATE_TRANSITION');assert.deepEqual(bytes(x),before);});
test('CAS invalid next schema stops before backup write',()=>{const x=setup(),s=x.repository.loadState().state,n=clone(s);n.missions.daily.resultCount=1;const before=bytes(x);code(()=>x.repository.commitStateTransition(s,n,()=>true),'INVALID_STATE');assert.deepEqual(bytes(x),before);});
for(const [key,name] of [[repoApi.KEYS.backup,'backup'],[repoApi.KEYS.state,'state']])test('CAS '+name+' read-back mismatch stops with no subsequent write',()=>{const x=setup(),s=x.repository.loadState().state,n=clone(s);n.profile.points++;x.storage.faults.dropKey=key;const w=x.storage.writes;code(()=>x.repository.commitStateTransition(s,n,()=>true),'STORAGE_VERIFY_FAILED');assert.equal(x.storage.writes-w,key===repoApi.KEYS.backup?1:2);});
test('CAS identical next is idempotent no write',()=>{const x=setup(),s=x.repository.loadState().state,w=x.storage.writes;x.repository.commitStateTransition(s,clone(s),()=>true);assert.equal(x.storage.writes,w);});
test('Daily completion commits points immediately once; duplicate has zero writes',()=>{const x=setup(),before=x.repository.loadState().state;const next=x.coordinator.completeMission('daily','daily_1');assert.equal(next.profile.points,before.profile.points+7);assert.equal(next.missions.daily.resultCount,1);const w=x.storage.writes;x.coordinator.completeMission('daily','daily_1');assert.equal(x.storage.writes,w);});
test('Weekly completion HOLD changes no State or storage',()=>{const x=setup(),before=bytes(x),w=x.storage.writes;code(()=>x.coordinator.completeMission('weekly','weekly_1'),'WEEKLY_COMPLETION_POINT_POLICY_UNRESOLVED');assert.equal(x.storage.writes,w);assert.deepEqual(bytes(x),before);});
test('Special completion HOLD creates no points/reward/damage',()=>{const x=setup(),before=bytes(x),w=x.storage.writes;code(()=>x.coordinator.completeMission('special','s1'),'SPECIAL_COMPLETION_STAGE3C_HOLD');assert.equal(x.storage.writes,w);assert.deepEqual(bytes(x),before);});
test('unresolved reserved forbids Daily and calendar mutation regardless of day',()=>{const x=setup();const record=op('reserved');record.dailyAttack.dayKey='2026-09-26';x.setOperation(record);const before=bytes(x);code(()=>x.coordinator.completeMission('daily','daily_1'),'ATTACK_RESERVATION_UNRESOLVED');code(()=>x.coordinator.advanceCalendar(),'ATTACK_RESERVATION_UNRESOLVED');assert.deepEqual(bytes(x),before);});
test('operation read failure does not mutate State',()=>{const x=setup();x.options.operationRepository.load=()=>{throw Error('read');};const before=bytes(x);assert.throws(()=>x.coordinator.completeMission('daily','daily_1'));assert.deepEqual(bytes(x),before);});
test('stale Daily completion does not advance Calendar',()=>{const x=setup();x.options.clock=()=> '2026-09-28T00:00:00+09:00';const c=coordinatorApi.create(x.options),before=bytes(x);code(()=>c.completeMission('daily','daily_1'),'DAILY_STATE_STALE');assert.deepEqual(bytes(x),before);});
test('minimal cannot operate; trusted path initializes without migration inference',()=>{const s=minimal();s.profile.currentAreaId='fixture-area';const x=setup(s),before=bytes(x);code(()=>x.coordinator.completeMission('daily','daily_1'),'MISSION_LIFECYCLE_UNINITIALIZED');assert.deepEqual(bytes(x),before);const next=x.coordinator.initializeMissions(configuration());assert.equal(next.missions.daily.resultCount,0);assert.equal(schema.validateState(next).ok,true);});
test('null area initialization is unresolved, no fields inferred',()=>{const x=setup(minimal()),before=bytes(x);code(()=>x.coordinator.initializeMissions(configuration()),'MISSION_LIFECYCLE_UNINITIALIZED');assert.deepEqual(bytes(x),before);});
test('Daily ATTACK after-completion changes only three allowed fields, no recalculation',()=>{const x=setup();x.coordinator.completeMission('daily','daily_1');let calculations=0;const controller=controllerApi.create({repository:x.repository,calculateBattle:(...a)=>{calculations++;return calculator.calculateBattle(...a);}});const input={battleId:'stage3-battle',battleDate:'2026-09-27',dailyResult:1,attackerSkillId:null,leaderCharacterId:null};controller.attack(input,definitions,'stage3-seed');const pending=x.repository.loadPending();controller.skip();x.setOperation(op('consumed'));const before=x.repository.loadState().state,recordBefore=clone(x.options.operationRepository.load());const after=x.coordinator.completeMission('daily','daily_2');assert.equal(calculations,1);assert.equal(after.profile.points,before.profile.points+14);const mask=s=>{const n=clone(s);delete n.profile.points;delete n.missions.daily.completedIds;delete n.missions.daily.resultCount;return n;};assert.deepEqual(mask(after),mask(before));assert.deepEqual(x.options.operationRepository.load(),recordBefore);assert.equal(recordBefore.dailyAttack.dailyResult,1);assert.deepEqual(clone(pending.finalSnapshot),clone(before));});
test('Battle pending blocks CAS and completion, including malformed pending',()=>{const x=setup();x.coordinator.completeMission('daily','daily_1');const state=x.repository.loadState().state,result=calculator.calculateBattle(state,{battleId:'pending-stage3',battleDate:'2026-09-27',dailyResult:1,attackerSkillId:null,leaderCharacterId:null},definitions,'pending');x.repository.persistPending(repoApi.createPending(state,result));const before=bytes(x);code(()=>x.coordinator.completeMission('daily','daily_2'),'NON_BATTLE_PENDING');code(()=>x.repository.commitStateTransition(state,state,()=>true),'NON_BATTLE_PENDING');assert.deepEqual(bytes(x),before);x.storage.map.set(repoApi.KEYS.pending,'bad');code(()=>x.coordinator.advanceCalendar(),'MALFORMED_PENDING');});
test('Mission additive fields and Weekly clearCount survive Battle finalSnapshot/replay/reload',()=>{const s=initialized().state;s.missions.weekly.completedIds=['weekly_1'];s.missions.weekly.clearCount=1;const x=setup(s),start=x.repository.loadState().state;let calculations=0;const controller=controllerApi.create({repository:x.repository,calculateBattle:(...a)=>{calculations++;return calculator.calculateBattle(...a);}});controller.attack({battleId:'stage3-replay',battleDate:'2026-09-27',dailyResult:1,attackerSkillId:null,leaderCharacterId:null},definitions,'replay');const pending=x.repository.loadPending();assert.deepEqual(clone(pending.finalSnapshot.missions),clone(start.missions));assert.equal(events.replayBattleEvents(start,pending.events,pending.finalSnapshot).matchesExpected,true);const reloaded=controllerApi.create({repository:x.repository,calculateBattle:()=>{throw Error('forbidden');}});reloaded.recover();reloaded.skip();assert.deepEqual(clone(x.repository.loadState().state.missions),clone(start.missions));assert.equal(calculations,1);});
test('Calendar same-day no-op never asks latest Mission settings or provider',()=>{const x=setup();x.options.missionConfigurationProvider={forPeriod:()=>{throw Error('latest setting forbidden');}};x.options.dailyEncounterProvider={forDate:()=>{throw Error('no spawn needed');}};const c=coordinatorApi.create(x.options),w=x.storage.writes;c.advanceCalendar();assert.equal(x.storage.writes,w);});
test('offline multiple days simulate pure, then exactly one CAS (two writes)',()=>{const x=setup();x.options.clock=()=> '2026-09-30T12:00:00+09:00';const calls=[];x.options.dailyEncounterProvider={forDate:c=>{calls.push(c.date);return descriptor(c.date);}};const c=coordinatorApi.create(x.options),before=x.repository.loadState().state,bytesBefore=bytes(x),w=x.storage.writes;const preview=c.simulateCalendar(before);assert.deepEqual(bytes(x),bytesBefore);assert.equal(preview.calendar.localDate,'2026-09-30');assert.deepEqual(calls,['2026-09-28','2026-09-29','2026-09-30']);const committed=c.advanceCalendar();assert.deepEqual(clone(committed),clone(preview));assert.equal(x.storage.writes-w,2);assert.equal(committed.revision,before.revision);assert.equal(committed.writtenAt,before.writtenAt);assert.deepEqual(clone(committed.missions.weekly),clone(before.missions.weekly));assert.deepEqual(clone(committed.missions.special),clone(before.missions.special));});
test('week boundary after prior simulated day causes zero storage commits',()=>{const x=setup();x.options.clock=()=> '2026-09-30T12:00:00+09:00';x.options.boundaryProvider={forDate:c=>({date:c.date,weekKey:c.date==='2026-09-29'?'new-week':c.weekKey})};const c=coordinatorApi.create(x.options),before=bytes(x),w=x.storage.writes;code(()=>c.advanceCalendar(),'WEEK_ROLLOVER_STAGE3B_HOLD');assert.equal(x.storage.writes,w);assert.deepEqual(bytes(x),before);});
test('Myart unresolved day effect stops before date/points/Enemy write',()=>{const x=setup();const s=x.repository.loadState().state;s.charactersById.myart={characterId:'myart',hp:500,sp:0,barrier:null,statusIds:[],resources:{reserveSp:1},flags:{},weekly:{},battle:null};x.storage.map.set(repoApi.KEYS.state,JSON.stringify(s));x.options.clock=()=> '2026-09-28T12:00:00+09:00';const before=bytes(x);code(()=>coordinatorApi.create(x.options).advanceCalendar(),'DAY_BOUNDARY_EFFECT_UNRESOLVED');assert.deepEqual(bytes(x),before);});
test('unconfigured Daily provider stops date/Mission reset as one transition',()=>{const x=setup();x.options.clock=()=> '2026-09-28T12:00:00+09:00';x.options.dailyEncounterProvider=null;const before=bytes(x);code(()=>coordinatorApi.create(x.options).advanceCalendar(),'DAILY_ENCOUNTER_UNCONFIGURED');assert.deepEqual(bytes(x),before);});
test('rollover swaps latest snapshot only at boundary; Special stays frozen',()=>{const x=setup(),slots=configuration().daily.slots.map(s=>({...s,assignmentRef:s.assignmentRef+'-next',pointValue:5}));slots.forEach(s=>x.options.assignmentRefPolicy.records.set(s.assignmentRef,{immutable:true,pointValue:s.pointValue,content:{label:'next'}}));let requests=0;x.options.missionConfigurationProvider={forPeriod:()=>{requests++;return {slots};}};const before=x.repository.loadState().state;x.coordinator.completeMission('daily','daily_1');assert.equal(requests,0);x.options.clock=()=> '2026-09-28T12:00:00+09:00';const next=coordinatorApi.create(x.options).advanceCalendar();assert.equal(requests,1);assert.equal(next.missions.daily.slots[0].pointValue,5);assert.deepEqual(clone(next.missions.special),clone(before.missions.special));});
console.log(`# ${passed}/${total} Stage 3 Integration tests passed`);
