'use strict';
const {assert,code,clone,initialized}=require('./stage3-mission-lifecycle.test.js');
const calendarApi=require('../../js/v2/calendar-lifecycle.js');
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3 Calendar: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3 Calendar: '+name+'\n'+e.stack);}}
const calendar=()=>calendarApi.create({clock:()=> '2026-09-28T12:00:00+09:00',boundaryProvider:{forDate:c=>({date:c.date,weekKey:c.weekKey,areaId:'fixture-area',areaWeekIndex:1,weekRole:'weekly'})}});
test('Asia/Tokyo midnight conversion and freshness',()=>{assert.equal(calendarApi.currentDay(()=> '2026-09-27T14:59:59Z'),'2026-09-27');assert.equal(calendarApi.currentDay(()=> '2026-09-27T15:00:00Z'),'2026-09-28');code(()=>calendar().assertFresh(initialized().state),'DAILY_STATE_STALE');});
test('boundary requires trusted weekKey; no local week formula',()=>{code(()=>calendarApi.create({clock:()=>0}).step(initialized().state),'CALENDAR_BOUNDARY_UNCONFIGURED');const c=calendarApi.create({clock:()=>0,boundaryProvider:{forDate:()=>({date:'2026-09-28'})}});code(()=>c.step(initialized().state),'WEEK_CONTEXT_UNCONFIGURED');});
test('incomplete trusted week context stops before any rollover',()=>{const c=calendarApi.create({clock:()=>0,boundaryProvider:{forDate:x=>({date:x.date,weekKey:'new-trusted-week'})}});code(()=>c.step(initialized().state),'WEEK_CONTEXT_UNCONFIGURED');});
test('day effect preserves SU, dailySuUsedOn, Defender carry, statuses and debt/eight marks',()=>{const s=initialized().state;s.battleProgress.suPoints=4;s.battleProgress.dailySuUsedOn='2026-09-27';s.leaderCarry.defenderDamageReductionByCharacterId={aria:{multiplier:.5,remainingUses:1}};s.statusInstances={final:{statusId:'finalHour',counters:{mainActionMarks:3}}};s.charactersById.aria.resources.debtBySourceId={enemy:{damage:123,mainActionMarks:4}};const before=clone(s),next=calendar().step(s);assert.deepEqual(clone(next.battleProgress),before.battleProgress);assert.deepEqual(clone(next.leaderCarry),before.leaderCarry);assert.deepEqual(clone(next.statusInstances),before.statusInstances);assert.deepEqual(clone(next.charactersById),before.charactersById);assert.deepEqual(clone(next.enemiesById),before.enemiesById);assert.deepEqual(clone(next.missions.weekly),before.missions.weekly);assert.deepEqual(clone(next.missions.special),before.missions.special);assert.equal(s.calendar.localDate,'2026-09-27');});
for(const [expiresOn,amount] of [['2026-09-28',3],['2026-09-29',3],['2026-09-27',null]])test('Elliott expiresOn '+expiresOn+' respects saved deadline',()=>{const s=initialized().state;s.battleProgress.pendingElliottHits={amount:3,expiresOn};const next=calendar().step(s);assert.equal(next.battleProgress.pendingElliottHits.amount,amount);assert.equal(s.battleProgress.pendingElliottHits.amount,3);});
for(const hits of [{amount:3,expiresOn:null},{amount:null,expiresOn:'2026-09-28'},{amount:3,expiresOn:'bad'},{amount:1.5,expiresOn:'2026-09-28'},null])test('malformed Elliott fails closed '+JSON.stringify(hits),()=>{const s=initialized().state;s.battleProgress.pendingElliottHits=hits;code(()=>calendar().step(s),'DAY_BOUNDARY_EFFECT_UNRESOLVED');assert.equal(s.calendar.localDate,'2026-09-27');});
test('active Myart reserveSp unresolved; zero/null unchanged',()=>{for(const reserveSp of [0,null,1,'unknown']){const s=initialized().state;s.charactersById.myart={resources:{reserveSp},flags:{}};if(reserveSp===0||reserveSp===null)assert.equal(calendar().step(s).charactersById.myart.resources.reserveSp,reserveSp);else code(()=>calendar().step(s),'DAY_BOUNDARY_EFFECT_UNRESOLVED');}});
test('unknown active date-bound effect/Linnet flag stops without inventing field',()=>{for(const change of [s=>s.charactersById.linnet.flags.someDailyUse=true,s=>s.charactersById.aria.resources.unknown={expiresOn:'2026-09-28'}]){const s=initialized().state;change(s);const before=JSON.stringify(s);code(()=>calendar().step(s),'DAY_BOUNDARY_EFFECT_UNRESOLVED');assert.equal(JSON.stringify(s),before);}});
test('invalid clock/timezone/date stop',()=>{code(()=>calendarApi.currentDay(()=> 'bad'),'CALENDAR_DATE_UNRESOLVED');const s=initialized().state;s.calendar.timezone='UTC';code(()=>calendar().step(s),'CALENDAR_DATE_UNRESOLVED');s.calendar.timezone='Asia/Tokyo';s.calendar.localDate='2026-02-30';code(()=>calendar().step(s),'CALENDAR_DATE_UNRESOLVED');});
test('opaque daily Enemy ID preserves Aria debt and eight-mark progress at Tokyo midnight',()=>{const s=initialized().state;s.charactersById.aria.resources.debtBySourceId={'daily-2026-10-05':{damage:123,mainActionMarks:4,sourceId:'daily-2026-10-05'}};s.statusInstances.final={statusId:'finalHour',counters:{mainActionMarks:3}};const before=clone(s),next=calendar().step(s);assert.deepEqual(clone(next.charactersById.aria),before.charactersById.aria);assert.deepEqual(clone(next.statusInstances),before.statusInstances);assert.equal(next.calendar.localDate,'2026-09-28');assert.deepEqual(clone(s),before);});
console.log(`# ${passed}/${total} Stage 3 Calendar tests passed`);
module.exports={calendar};
