'use strict';
const assert=require('node:assert/strict');
const schema=require('../../js/v2/schema.js'),missionApi=require('../../js/v2/mission-lifecycle.js'),events=require('../../js/v2/battle-events.js');
const entry=require('../../js/v2/production-verification-entry.js');
const v2={characters:require('../../data/v2/characters.js'),enemies:require('../../data/v2/enemies.js'),skills:require('../../data/v2/skills.js'),statusEffects:require('../../data/v2/status-effects.js'),battleRules:require('../../data/v2/battle-rules.js'),missions:require('../../data/v2/missions.js'),saveMigration:require('../../js/v2/save-migration.js')};
const clone=v=>JSON.parse(JSON.stringify(v));
const code=(fn,name)=>assert.throws(fn,e=>e.code===name);
function minimal(){return entry.fixtureState(v2);}
// Explicit trusted fixture values/references, not a production ID/points policy.
function configuration(){const slots=kind=>[1,2,3].map(i=>({slotId:kind+'_'+i,assignmentRef:'fixture-'+kind+'-'+i,pointValue:i*7}));return {daily:{slots:slots('daily'),completedIds:[]},weekly:{slots:slots('weekly'),completedIds:[]},special:{areaId:'fixture-area',slots:[],completedIds:[]}};}
function policy(config=configuration()){const records=new Map();for(const group of Object.values(config))for(const slot of group.slots)records.set(slot.assignmentRef,{immutable:true,pointValue:slot.pointValue,content:{label:slot.slotId}});return {records,resolveImmutable:ref=>clone(records.get(ref)||{immutable:false})};}
function initialized(){const state=minimal();state.profile.currentAreaId='fixture-area';const config=configuration(),p=policy(config),mission=missionApi.create({assignmentRefPolicy:p});return {state:mission.initialize(state,config),config,policy:p,mission};}
function memory(){const map=new Map(),faults={};let writes=0;return {map,faults,get writes(){return writes;},getItem:k=>{if(faults.readKey===k)throw Error('read');return map.get(k)??null;},setItem:(k,v)=>{writes++;if(faults.writeKey===k)throw Error('write');if(faults.dropKey!==k)map.set(k,v);},removeItem:k=>map.delete(k)};}
let passed=0,total=0;
function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3 Mission: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3 Mission: '+name+'\n'+e.stack);}}
test('minimal migration State stays valid at schemaVersion 2',()=>{const s=minimal();assert.equal(schema.validateState(s).ok,true);assert.equal(schema.validateMissions(s).initialized,false);assert.equal(s.schemaVersion,2);});
test('trusted initialized State is valid with all three snapshots',()=>{const x=initialized();assert.equal(schema.validateState(x.state).ok,true);assert.equal(schema.validateMissions(x.state).initialized,true);});
test('partial initialization rejected',()=>{const s=minimal();s.missions.daily.slots=configuration().daily.slots;assert.equal(schema.validateState(s).ok,false);});
for(const kind of ['daily','weekly'])test(kind+' exactly three slots',()=>{const s=initialized().state;s.missions[kind].slots.pop();assert.equal(schema.validateState(s).ok,false);});
for(const kind of ['daily','weekly','special'])test(kind+' duplicate slots/completed IDs/subset rejected',()=>{let s=initialized().state;if(kind==='special')s.missions.special.slots=configuration().daily.slots;s.missions[kind].slots[1]=clone(s.missions[kind].slots[0]);assert.equal(schema.validateState(s).ok,false);s=initialized().state;s.missions[kind].completedIds=['missing'];assert.equal(schema.validateState(s).ok,false);s=initialized().state;s.missions[kind].completedIds=[kind+'_1',kind+'_1'];assert.equal(schema.validateState(s).ok,false);});
test('Special zero through three slots valid; four rejected',()=>{for(let n=0;n<=4;n++){const s=initialized().state;s.missions.special.slots=Array.from({length:n},(_,i)=>({slotId:'s'+i,assignmentRef:'test-'+i,pointValue:i}));assert.equal(schema.validateState(s).ok,n<=3);}});
for(const [name,change] of [['Daily resultCount',s=>s.missions.daily.resultCount=1],['Weekly clearCount',s=>s.missions.weekly.clearCount=1],['Daily/calendar date',s=>s.missions.daily.date='2026-09-26'],['Weekly/calendar week',s=>s.missions.weekly.weekKey='other'],['Special/profile area',s=>s.missions.special.areaId='other'],['null area',s=>s.profile.currentAreaId=null]])test(name+' invariant enforced',()=>{const s=initialized().state;change(s);assert.equal(schema.validateState(s).ok,false);});
test('uninitialized/null area cannot be operated or inferred from legacy counters',()=>{const m=missionApi.create({assignmentRefPolicy:policy()});code(()=>m.completeDaily(minimal(),'daily_1'),'MISSION_LIFECYCLE_UNINITIALIZED');code(()=>m.initialize(minimal(),configuration()),'MISSION_LIFECYCLE_UNINITIALIZED');const s=minimal();s.profile.currentAreaId='fixture-area';code(()=>m.initialize(s,{daily:configuration().daily}),'MISSION_LIFECYCLE_UNINITIALIZED');});
test('assignment policy required and mutable references rejected',()=>{const s=initialized().state;code(()=>missionApi.create({}).completeDaily(s,'daily_1'),'MISSION_ASSIGNMENT_REF_POLICY_UNCONFIGURED');code(()=>missionApi.create({assignmentRefPolicy:{resolveImmutable:()=>({immutable:false})}}).completeDaily(s,'daily_1'),'MISSION_ASSIGNMENT_REF_NOT_IMMUTABLE');});
test('same assignmentRef redefinition rejects points or content changes',()=>{const x=initialized(),ref=x.state.missions.daily.slots[0].assignmentRef;x.policy.records.get(ref).content.label='changed';code(()=>x.mission.completeDaily(x.state,'daily_1'),'MISSION_ASSIGNMENT_REF_REDEFINED');const y=initialized();y.policy.records.get(ref).pointValue++;code(()=>y.mission.completeDaily(y.state,'daily_1'),'MISSION_ASSIGNMENT_REF_REDEFINED');});
test('active slots/point snapshot frozen; latest configuration is not consulted',()=>{const x=initialized();x.config.daily.slots[0].pointValue=900;const next=x.mission.completeDaily(x.state,'daily_1');assert.equal(next.profile.points,x.state.profile.points+7);assert.equal(next.missions.daily.slots[0].pointValue,7);});
test('Daily completion immediate points, duplicate no double grant',()=>{const x=initialized(),next=x.mission.completeDaily(x.state,'daily_2');assert.equal(next.profile.points,x.state.profile.points+14);assert.equal(next.missions.daily.resultCount,1);assert.deepEqual(clone(x.mission.completeDaily(next,'daily_2')),clone(next));assert.equal(x.state.missions.daily.resultCount,0);});
test('unsafe point snapshot/profile/sum rejected with source unchanged',()=>{for(const change of [x=>x.state.profile.points=Number.MAX_SAFE_INTEGER+1,x=>x.state.profile.points=Number.MAX_SAFE_INTEGER,x=>x.state.missions.daily.slots[0].pointValue=Number.MAX_SAFE_INTEGER+1]){const x=initialized();change(x);const bytes=JSON.stringify(x.state);code(()=>x.mission.completeDaily(x.state,'daily_1'),'MISSION_POINT_UNSAFE');assert.equal(JSON.stringify(x.state),bytes);}});
test('rollover inherits valid immutable snapshot, resets Daily only',()=>{const x=initialized(),s=x.mission.completeDaily(x.state,'daily_1'),next=x.mission.rolloverDaily(s,'2026-09-28',null);assert.equal(next.missions.daily.resultCount,0);assert.deepEqual(clone(next.missions.daily.slots),clone(s.missions.daily.slots));assert.deepEqual(clone(next.missions.weekly),clone(s.missions.weekly));assert.deepEqual(clone(next.missions.special),clone(s.missions.special));});
test('period replacement only via supplied immutable snapshot',()=>{const x=initialized(),slots=x.config.daily.slots.map(s=>({...s,assignmentRef:s.assignmentRef+'-new',pointValue:2}));slots.forEach(s=>x.policy.records.set(s.assignmentRef,{immutable:true,pointValue:s.pointValue,content:{label:'new'}}));const next=x.mission.rolloverDaily(x.state,'2026-09-28',{slots});assert.equal(next.missions.daily.slots[0].pointValue,2);assert.equal(x.state.missions.daily.slots[0].pointValue,7);});
console.log(`# ${passed}/${total} Stage 3 Mission tests passed`);
module.exports={assert,code,clone,minimal,configuration,policy,initialized,memory,v2,events};
