'use strict';
const {assert,code,clone,initialized,v2}=require('./stage3-mission-lifecycle.test.js');
const enemyApi=require('../../js/v2/enemy-lifecycle.js'),entry=require('../../js/v2/production-verification-entry.js');
const definitions=entry.definitions(v2);
// Fully materialized fixture only; lifecycle production code supplies no HP,
// enemy class, action profile or status defaults.
function descriptor(date='2026-09-28',instanceId='fixture-'+date,descriptorId='enc-'+date){return {instanceId,encounterDescriptorId:descriptorId,spawnedOn:date,kind:'daily',definitionId:'daily_base',enemy:{instanceId,definitionId:'daily_base',kind:'daily',hp:800,maxHp:800,barrier:null,phase:{current:null,pending:null,pendingAppliesAt:null},statusIds:[],spawnedOn:date,defeated:false,flags:{encounterDescriptorId:descriptorId}}};}
function spawnState(){const s=initialized().state;s.calendar.localDate='2026-09-28';s.missions.daily.date='2026-09-28';s.calendar.enemySpawnDate='2026-09-27';return s;}
const provider={forDate:c=>descriptor(c.date)};
const enemy=(p=provider,defs=definitions)=>enemyApi.create({dailyEncounterProvider:p,definitions:defs});
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3 Enemy: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3 Enemy: '+name+'\n'+e.stack);}}
test('provider mandatory',()=>code(()=>enemy(null).spawn(spawnState()),'DAILY_ENCOUNTER_UNCONFIGURED'));
for(const [name,mutate] of [['empty',d=>null],['missing HP',d=>{delete d.enemy.hp;return d;}],['missing phase',d=>{delete d.enemy.phase;return d;}],['unknown definition',d=>{d.definitionId=d.enemy.definitionId='missing';return d;}],['kind mismatch',d=>{d.definitionId=d.enemy.definitionId='weekly_base';return d;}],['invalid materialized HP',d=>{d.enemy.hp=10000;return d;}],['missing identity',d=>{delete d.encounterDescriptorId;return d;}]])test(name+' descriptor stops without compensation',()=>{const s=spawnState(),before=JSON.stringify(s);code(()=>enemy({forDate:()=>mutate(descriptor())}).spawn(s),'DAILY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED');assert.equal(JSON.stringify(s),before);});
test('pure spawn, identical retries and single descriptor binding',()=>{const s=spawnState(),before=JSON.stringify(s),one=enemy().spawn(s),two=enemy().spawn(s),retry=enemy().spawn(one);assert.deepEqual(clone(one),clone(two));assert.deepEqual(clone(retry),clone(one));assert.equal(JSON.stringify(s),before);assert.equal(one.enemyOrder.filter(k=>k==='fixture-2026-09-28').length,1);assert.equal(one.calendar.enemySpawnDate,'2026-09-28');});
for(const key of ['instanceId','spawnedOn','kind','encounterDescriptorId','definitionId'])test('existing instance collision '+key+' never overwrites',()=>{const s=spawnState(),d=descriptor();s.enemiesById[d.instanceId]=clone(d.enemy);s.enemyOrder.push(d.instanceId);s.calendar.enemySpawnDate=d.spawnedOn;(key==='encounterDescriptorId'?s.enemiesById[d.instanceId].flags:s.enemiesById[d.instanceId])[key]=key==='kind'?'weekly':'other';const before=JSON.stringify(s);code(()=>enemy().spawn(s),'ENCOUNTER_INSTANCE_CONFLICT');assert.equal(JSON.stringify(s),before);});
test('same descriptor same day different instance binding conflict',()=>{const s=enemy().spawn(spawnState());code(()=>enemy({forDate:()=>descriptor('2026-09-28','other','enc-2026-09-28')}).spawn(s),'ENCOUNTER_INSTANCE_CONFLICT');});
test('same instance prior day, Weekly or Boss collisions stop',()=>{for(const kind of ['daily','weekly','areaBoss']){const s=spawnState(),d=descriptor();s.enemiesById[d.instanceId]={...d.enemy,kind,spawnedOn:'2026-09-27'};s.enemyOrder.push(d.instanceId);code(()=>enemy().spawn(s),'ENCOUNTER_INSTANCE_CONFLICT');}});
for(const ledger of ['2026-09-28','2026-09-29','bad'])test('unbound/future/malformed ledger '+ledger+' stops',()=>{const s=spawnState();s.calendar.enemySpawnDate=ledger;code(()=>enemy().spawn(s),'DAILY_SPAWN_LEDGER_CONFLICT');});
test('matching instance but stale ledger stops rather than respawning',()=>{const s=enemy().spawn(spawnState());s.calendar.enemySpawnDate='2026-09-27';code(()=>enemy().spawn(s),'DAILY_SPAWN_LEDGER_CONFLICT');});
function full(withBoss){const s=spawnState();s.enemiesById={};s.enemyOrder=[];for(let i=1;i<=5;i++){const d=descriptor('2026-09-'+String(20+i),'old-'+i);s.enemiesById[d.instanceId]=d.enemy;s.enemyOrder.push(d.instanceId);}if(withBoss){const boss=clone(s.enemiesById['old-5']);delete s.enemiesById['old-5'];s.enemyOrder=s.enemyOrder.filter(k=>k!=='old-5');boss.instanceId='boss';boss.kind='weekly';boss.definitionId='weekly_base';boss.spawnedOn=null;delete boss.flags.encounterDescriptorId;s.enemiesById.boss=boss;s.enemyOrder.push('boss');}return s;}
test('oldest Daily eviction enforces total five without Boss',()=>{const next=enemy().spawn(full(false));assert.equal(next.enemyOrder.length,5);assert.equal(next.enemiesById['old-1'],undefined);});
test('Boss preserved and Daily at most four',()=>{const s=full(true),before=clone(s.enemiesById.boss),next=enemy().spawn(s);assert.deepEqual(clone(next.enemiesById.boss),before);assert.equal(next.enemyOrder.length,5);assert.equal(next.enemyOrder.filter(k=>next.enemiesById[k].kind==='daily').length,4);});
test('source-status eviction reference stops entire transition',()=>{const s=full(false);s.statusInstances.poison={statusId:'poison',ownerType:'character',ownerId:'aria',sourceType:'enemy',sourceId:'old-1'};const before=JSON.stringify(s);code(()=>enemy().spawn(s),'ENEMY_EVICTION_SOURCE_STATUS_UNRESOLVED');assert.equal(JSON.stringify(s),before);});
test('enemy-owned status also cannot be silently removed',()=>{const s=full(false);s.statusInstances.poison={statusId:'poison',ownerType:'enemy',ownerId:'old-1',sourceType:'character',sourceId:'aria'};code(()=>enemy().spawn(s),'ENEMY_EVICTION_SOURCE_STATUS_UNRESOLVED');});
test('ambiguous oldest or missing date stops',()=>{for(const date of ['2026-09-21',null]){const s=full(false);s.enemiesById['old-2'].spawnedOn=date;code(()=>enemy().spawn(s),'ENEMY_ORDER_UNRESOLVED');}});
test('identity lives in flags; legacy Enemy needs no descriptor top-level',()=>{const s=spawnState();assert.equal(require('../../js/v2/schema.js').validateState(s).ok,true);const next=enemy().spawn(s),record=next.enemiesById['fixture-2026-09-28'];assert.equal(record.flags.encounterDescriptorId,'enc-2026-09-28');assert.equal(Object.hasOwn(record,'encounterDescriptorId'),false);assert.equal(require('../../js/v2/schema.js').validateState(next).ok,true);record.encounterDescriptorId='forbidden';assert.equal(require('../../js/v2/schema.js').validateState(next).ok,false);});
console.log(`# ${passed}/${total} Stage 3 Enemy tests passed`);
module.exports={descriptor,definitions,provider};
