'use strict';
const {assert,code,clone,initialized}=require('./stage3-mission-lifecycle.test.js');
const {descriptor,definitions}=require('./stage3-enemy-lifecycle.test.js');
const {state,context,character,setup,stop}=require('./stage3b-week-lifecycle.test.js');
const enemy=require('../../js/v2/enemy-lifecycle.js'),calendar=require('../../js/v2/calendar-lifecycle.js'),week=require('../../js/v2/week-lifecycle.js');
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('ok - Stage 3B Enemy: '+name);}catch(e){process.exitCode=1;console.error('not ok - Stage 3B Enemy: '+name+'\n'+e.stack);}}
function daily(c){const d=descriptor(c.date);if(c.state.calendar.weekContext.areaWeekIndex===4){d.encounterRole='degradedWeeklyClone';delete d.enemy.flags.encounterRole;d.sourceEncounterDescriptorId=c.state.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId;}return d;}
function spawnState(index=1){const s=state(index);s.enemiesById={};s.enemyOrder=[];s.calendar.enemySpawnDate=null;return s;}
function spawn(s,p={forDate:daily}){return enemy.create({dailyEncounterProvider:p,definitions}).spawn(s);}
for(const index of [1,2,3,4])test('week '+index+' persistent role/descriptor/source and pure retry',()=>{const s=spawnState(index),old=clone(s),n=spawn(s),e=n.enemiesById['fixture-'+s.calendar.localDate];assert.equal(e.flags.encounterRole,index===4?'degradedWeeklyClone':'standardDaily');assert.equal(e.flags.encounterDescriptorId,'enc-'+s.calendar.localDate);assert.equal(e.flags.sourceEncounterDescriptorId,index===4?'source-week3':undefined);assert.equal(Object.hasOwn(e,'encounterDescriptorId'),false);assert.deepEqual(clone(spawn(n)),clone(n));assert.deepEqual(clone(s),old);assert.equal(e.hp,800);assert.equal(e.maxHp,800);});
for(const change of [d=>d.encounterRole='standardDaily',d=>delete d.encounterRole,d=>delete d.sourceEncounterDescriptorId,d=>d.sourceEncounterDescriptorId='wrong'])test('week4 untrusted role/source STOP no compensation',()=>{const s=spawnState(4),before=clone(s);code(()=>spawn(s,{forDate:c=>{const d=daily(c);change(d);return d;}}),'DEGRADED_WEEKLY_DESCRIPTOR_UNRESOLVED');assert.deepEqual(clone(s),before);});
for(const index of [1,2,3])test('standard week '+index+' degraded role cannot substitute',()=>code(()=>spawn(spawnState(index),{forDate:c=>{const d=daily(c);d.encounterRole='degradedWeeklyClone';d.sourceEncounterDescriptorId='source';return d;}}),'DEGRADED_WEEKLY_DESCRIPTOR_UNRESOLVED'));
for(const [field,value] of [['encounterRole','standardDaily'],['sourceEncounterDescriptorId','wrong'],['encounterDescriptorId','wrong']])test('existing clone '+field+' drift collision not overwrite',()=>{const n=spawn(spawnState(4));n.enemiesById[n.enemyOrder[0]].flags[field]=value;const old=clone(n);code(()=>spawn(n),'ENCOUNTER_INSTANCE_CONFLICT');assert.deepEqual(clone(n),old);});
test('same descriptor new instance rebind conflict',()=>{const n=spawn(spawnState(4));code(()=>spawn(n,{forDate:c=>{const d=daily(c);d.instanceId=d.enemy.instanceId='rebound';return d;}}),'ENCOUNTER_INSTANCE_CONFLICT');});
test('reload preserves source authority, not reconstructed from definition/date',()=>{const s=spawnState(4);s.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId='opaque-immutable-source';const n=spawn(s);assert.equal(n.enemiesById[n.enemyOrder[0]].flags.sourceEncounterDescriptorId,'opaque-immutable-source');assert.deepEqual(clone(spawn(clone(n))),clone(n));});
test('week4 later days use saved source with one CAS per operation',()=>{const s=state(4),x=setup(s,'2026-09-29',c=>context(s,4,c.date));x.options.dailyEncounterProvider={forDate:daily};const w=x.storage.writes,n=x.api().advanceCalendar();assert.equal(x.storage.writes-w,2);assert.equal(n.calendar.weekContext.degradedWeeklySourceEncounterDescriptorId,'source-week3');for(const e of Object.values(n.enemiesById).filter(e=>e.spawnedOn>'2026-09-27'))assert.equal(e.flags.sourceEncounterDescriptorId,'source-week3');x.options.clock=()=> '2026-09-30T12:00:00+09:00';const reload=x.api().advanceCalendar();assert.equal(reload.enemiesById['fixture-2026-09-30'].flags.sourceEncounterDescriptorId,'source-week3');});
test('week4 later-day source mismatch leaves entire offline sequence uncommitted',()=>{const s=state(4),x=setup(s,'2026-09-29',c=>context(s,4,c.date));x.options.dailyEncounterProvider={forDate:c=>{const d=daily(c);if(c.date==='2026-09-29')d.sourceEncounterDescriptorId='wrong';return d;}};stop(x,'DEGRADED_WEEKLY_DESCRIPTOR_UNRESOLVED');});
test('trusted same-week context preserves enemy HP/alive/status and all characters',()=>{const s=state(),x=setup(s,'2026-09-28',c=>context(s,1,c.date)),old=clone(s);s.enemiesById[s.enemyOrder[0]].hp=1;const c=calendar.create(x.options),n=c.step(s);assert.deepEqual(clone(n.enemiesById),clone(s.enemiesById));assert.deepEqual(clone(n.charactersById),old.charactersById);assert.deepEqual(clone(n.statusInstances),old.statusInstances);assert.deepEqual(clone(n.missions.weekly),old.missions.weekly);});
test('Tokyo next day keeps Sierra coins/JACKPOT and materials, no daily field invented',()=>{const s=state();character(s,'sierra',{faceCoins:12,jackpot:true,coinTossAudit:{audit:1}});character(s,'myart',{researchKits:2,weaknessMaterials:{daily:3},otherMaterials:4,reserveSp:0});const before=clone(s.charactersById),n=calendar.dayBoundaryEffects(s,'2026-09-28');assert.deepEqual(clone(n.charactersById),before);assert.equal(Object.keys(n.charactersById.sierra.flags).length,0);});
test('unknown active Sierra day field STOP, opaque material map keys KEEP',()=>{const s=state();character(s,'sierra',{}, {firstCoinUsedToday:true});code(()=>calendar.dayBoundaryEffects(s,'2026-09-28'),'DAY_BOUNDARY_EFFECT_UNRESOLVED');delete s.charactersById.sierra.flags.firstCoinUsedToday;character(s,'myart',{weaknessMaterials:{'daily-until-expiry':{amount:2}},reserveSp:0});const n=calendar.dayBoundaryEffects(s,'2026-09-28');assert.deepEqual(clone(n.charactersById.myart.resources),clone(s.charactersById.myart.resources));});
test('week boundary Elliott next-day expiry preserved then expires later only',()=>{const s=state();s.battleProgress.pendingElliottHits={amount:5,expiresOn:'2026-09-28'};const n=week.resetCharacters(s,definitions);assert.deepEqual(clone(n.battleProgress.pendingElliottHits),s.battleProgress.pendingElliottHits);assert.equal(calendar.dayBoundaryEffects(n,'2026-09-28').battleProgress.pendingElliottHits.amount,5);assert.equal(calendar.dayBoundaryEffects(n,'2026-09-29').battleProgress.pendingElliottHits.amount,null);});
test('AreaBoss plus trusted Daily never spawns an additional Weekly Boss',()=>{const s=state(3);const d=descriptor(s.calendar.localDate,'old-weekly','source-week3');d.enemy.kind='weekly';d.enemy.definitionId='weekly_base';s.enemiesById={[d.instanceId]:d.enemy};s.enemyOrder=[d.instanceId];const x=setup(s);x.options.dailyEncounterProvider={forDate:daily};const n=x.api().advanceCalendar();assert.equal(Object.values(n.enemiesById).filter(e=>e.kind==='areaBoss').length,1);assert.equal(Object.values(n.enemiesById).filter(e=>e.kind==='weekly').length,0);});
test('4th-week encounter provider unavailable has write0, no daily_base fallback',()=>{const s=state(4),x=setup(s,'2026-09-28',c=>context(s,4,c.date));x.options.dailyEncounterProvider={forDate:()=>null};stop(x,'DAILY_ENCOUNTER_DESCRIPTOR_UNSUPPORTED');});
test('old Daily/Weekly/Area Boss records never survive week reset',()=>{const s=state();for(const kind of ['daily','weekly','areaBoss']){const d=descriptor(s.calendar.localDate,'old-'+kind);d.enemy.kind=kind;d.enemy.definitionId=kind==='daily'?'daily_base':kind==='weekly'?'weekly_base':'area_boss_base';s.enemiesById[d.instanceId]=d.enemy;s.enemyOrder.push(d.instanceId);}const n=week.resetCharacters(s,definitions);assert.deepEqual(clone(n.enemiesById),{});assert.deepEqual(n.enemyOrder,[]);});
test('Weekly and Special completion remain HOLD even after week transition',()=>{const x=setup();x.api().advanceCalendar();const before=[...x.storage.map],w=x.storage.writes;code(()=>x.api().completeMission('weekly','weekly_1'),'WEEKLY_COMPLETION_POINT_POLICY_UNRESOLVED');code(()=>x.api().completeMission('special','special_1'),'SPECIAL_COMPLETION_STAGE3C_HOLD');assert.equal(x.storage.writes,w);assert.deepEqual([...x.storage.map],before);});
console.log(`# ${passed}/${total} Stage 3B Enemy tests passed`);
